services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_frontend
    ports:
      - "5173:80"
    extra_hosts:
      - "backend:host-gateway"
    restart: unless-stopped
